#!/usr/bin/env bash
set -x

warn() {
	echo "$*" >&2
}

die() {
	warn "$@"
	exit 1
}

SRC_DIR=$1

SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

SERVER=$(jq -r '.source.server // ""' < $SCRIPT_INPUT)
PORT=$(jq -r '.source.port // ""' < $SCRIPT_INPUT)
DEST_DIR=$(jq -r '.source.base_dir // ""' < $SCRIPT_INPUT)
USER=$(jq -r '.source.user // ""' < $SCRIPT_INPUT)
SYNC_DIR=$(jq -r '.params.sync_dir // ""' < $SCRIPT_INPUT)

## check if port is set in the configuration and
## use default SSH port number 22 otherwise
PORT=${PORT:+ -p $PORT}

warn BUILD_ID=$BUILD_ID
warn BUILD_NAME=$BUILD_NAME
warn BUILD_JOB_NAME=$BUILD_JOB_NAME
warn BUILD_PIPELINE_NAME=$BUILD_PIPELINE_NAME
warn SERVER=$SERVER
warn PORT=$PORT
warn USER=$USER
warn SRC_DIR=$SRC_DIR
warn DEST_DIR=$DEST_DIR
warn SYNC_DIR=$SYNC_DIR

mkdir ~/.ssh
chmod 600 ~/.ssh
(jq -r '.source.private_key // empty' < $SCRIPT_INPUT) > ~/.ssh/server_key
printf 'Host %s\n\tStrictHostKeyChecking no\n' "$SERVER" >~/.ssh/config
chmod 600 ~/.ssh/*

eval $(ssh-agent >/dev/null)
SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key 1>&2 2>/dev/null

# Create the new directory for this build
ssh -i ~/.ssh/server_key$PORT $USER@$SERVER mkdir -p $DEST_DIR ||
	die "Failed to create destination $DEST_DIR"

rsync -Pav -e "ssh -i ~/.ssh/server_key$PORT" \
  $SRC_DIR/$SYNC_DIR/* $USER@$SERVER:$DEST_DIR >&2 ||
    die "Failed to rsync $SRC_DIR to $DEST_DIR"

printf '{"version": {"ref": "%s"}}\n' "$BUILD_PIPELINE_NAME/$BUILD_NAME:$BUILD_ID"
